services:
  mysql:
    image: mysql:8.0
    container_name: myBookInsight
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql/:/var/lib/mysql
    networks:
      - myBookInsight-network


volumes:
  mysql_data:

networks:
  myBookInsight-network:
    driver: bridge

